# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compra.ui',
# licensing of 'compra.ui' applies.
#
# Created: Sun Jan 13 01:36:07 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_CompraDialog(object):
    def setupUi(self, CompraDialog):
        CompraDialog.setObjectName("CompraDialog")
        CompraDialog.resize(693, 659)
        CompraDialog.setMinimumSize(QtCore.QSize(693, 650))
        CompraDialog.setMaximumSize(QtCore.QSize(693, 659))
        self.gridLayout_2 = QtWidgets.QGridLayout(CompraDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(CompraDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.codigoFacturaLineEdit = QtWidgets.QLineEdit(CompraDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.codigoFacturaLineEdit.setFont(font)
        self.codigoFacturaLineEdit.setObjectName("codigoFacturaLineEdit")
        self.horizontalLayout_2.addWidget(self.codigoFacturaLineEdit)
        self.label_2 = QtWidgets.QLabel(CompraDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.proveedorLineEdit = QtWidgets.QLineEdit(CompraDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.proveedorLineEdit.setFont(font)
        self.proveedorLineEdit.setObjectName("proveedorLineEdit")
        self.horizontalLayout_2.addWidget(self.proveedorLineEdit)
        self.label_3 = QtWidgets.QLabel(CompraDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.dateEdit = QtWidgets.QDateEdit(CompraDialog)
        self.dateEdit.setMinimumSize(QtCore.QSize(120, 0))
        self.dateEdit.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.productoExistenteRadioButton = QtWidgets.QRadioButton(CompraDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.productoExistenteRadioButton.setFont(font)
        self.productoExistenteRadioButton.setObjectName("productoExistenteRadioButton")
        self.verticalLayout_2.addWidget(self.productoExistenteRadioButton)
        self.productoExistenteGroupBox = QtWidgets.QGroupBox(CompraDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.productoExistenteGroupBox.setFont(font)
        self.productoExistenteGroupBox.setStyleSheet("font: 11pt \".SF NS Text\";")
        self.productoExistenteGroupBox.setTitle("")
        self.productoExistenteGroupBox.setCheckable(False)
        self.productoExistenteGroupBox.setObjectName("productoExistenteGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.productoExistenteGroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.productoExistenteGroupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.codigoProductoExistenteLineEdit = QtWidgets.QLineEdit(self.productoExistenteGroupBox)
        self.codigoProductoExistenteLineEdit.setObjectName("codigoProductoExistenteLineEdit")
        self.horizontalLayout_4.addWidget(self.codigoProductoExistenteLineEdit)
        self.label_12 = QtWidgets.QLabel(self.productoExistenteGroupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.cantidadNuevoProductoLineEdit_2 = QtWidgets.QLineEdit(self.productoExistenteGroupBox)
        self.cantidadNuevoProductoLineEdit_2.setObjectName("cantidadNuevoProductoLineEdit_2")
        self.horizontalLayout_4.addWidget(self.cantidadNuevoProductoLineEdit_2)
        self.agregarProductoExistenteButton = QtWidgets.QPushButton(self.productoExistenteGroupBox)
        self.agregarProductoExistenteButton.setObjectName("agregarProductoExistenteButton")
        self.horizontalLayout_4.addWidget(self.agregarProductoExistenteButton)
        self.verticalLayout_2.addWidget(self.productoExistenteGroupBox)
        self.productoNuevoRadioButton = QtWidgets.QRadioButton(CompraDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.productoNuevoRadioButton.setFont(font)
        self.productoNuevoRadioButton.setObjectName("productoNuevoRadioButton")
        self.verticalLayout_2.addWidget(self.productoNuevoRadioButton)
        self.nuevoProductoGroupBox = QtWidgets.QGroupBox(CompraDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nuevoProductoGroupBox.setFont(font)
        self.nuevoProductoGroupBox.setStyleSheet("font: 11pt \".SF NS Text\";")
        self.nuevoProductoGroupBox.setTitle("")
        self.nuevoProductoGroupBox.setObjectName("nuevoProductoGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.nuevoProductoGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.codigoProductoNuevoLineEdit = QtWidgets.QLineEdit(self.nuevoProductoGroupBox)
        self.codigoProductoNuevoLineEdit.setObjectName("codigoProductoNuevoLineEdit")
        self.gridLayout.addWidget(self.codigoProductoNuevoLineEdit, 0, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.nuevoProductoGroupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.nuevoProductoGroupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.nuevoProductoGroupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.proveedorNuevoProductoLineEdit = QtWidgets.QLineEdit(self.nuevoProductoGroupBox)
        self.proveedorNuevoProductoLineEdit.setObjectName("proveedorNuevoProductoLineEdit")
        self.gridLayout.addWidget(self.proveedorNuevoProductoLineEdit, 0, 4, 1, 1)
        self.descripcionNuevoProductoLineEdit = QtWidgets.QLineEdit(self.nuevoProductoGroupBox)
        self.descripcionNuevoProductoLineEdit.setObjectName("descripcionNuevoProductoLineEdit")
        self.gridLayout.addWidget(self.descripcionNuevoProductoLineEdit, 1, 1, 1, 4)
        self.label_9 = QtWidgets.QLabel(self.nuevoProductoGroupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.precioListaNuevoProductoLineEdit = QtWidgets.QLineEdit(self.nuevoProductoGroupBox)
        self.precioListaNuevoProductoLineEdit.setObjectName("precioListaNuevoProductoLineEdit")
        self.gridLayout.addWidget(self.precioListaNuevoProductoLineEdit, 2, 1, 1, 2)
        self.agregarProductoNuevoButton = QtWidgets.QPushButton(self.nuevoProductoGroupBox)
        self.agregarProductoNuevoButton.setObjectName("agregarProductoNuevoButton")
        self.gridLayout.addWidget(self.agregarProductoNuevoButton, 3, 0, 1, 5)
        self.label_11 = QtWidgets.QLabel(self.nuevoProductoGroupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 3, 1, 1)
        self.cantidadNuevoProductoLineEdit = QtWidgets.QLineEdit(self.nuevoProductoGroupBox)
        self.cantidadNuevoProductoLineEdit.setObjectName("cantidadNuevoProductoLineEdit")
        self.gridLayout.addWidget(self.cantidadNuevoProductoLineEdit, 2, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.nuevoProductoGroupBox)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(CompraDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.productosCompraTableView = QtWidgets.QTableView(CompraDialog)
        self.productosCompraTableView.setMinimumSize(QtCore.QSize(0, 200))
        self.productosCompraTableView.setMaximumSize(QtCore.QSize(16777215, 200))
        self.productosCompraTableView.setObjectName("productosCompraTableView")
        self.verticalLayout_3.addWidget(self.productosCompraTableView)
        self.borrarProductoButton = QtWidgets.QPushButton(CompraDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.borrarProductoButton.setFont(font)
        self.borrarProductoButton.setObjectName("borrarProductoButton")
        self.verticalLayout_3.addWidget(self.borrarProductoButton)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okButton = QtWidgets.QPushButton(CompraDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(CompraDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)

        self.retranslateUi(CompraDialog)
        QtCore.QMetaObject.connectSlotsByName(CompraDialog)

    def retranslateUi(self, CompraDialog):
        CompraDialog.setWindowTitle(QtWidgets.QApplication.translate("CompraDialog", "Dialog", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("CompraDialog", "Codigo de Factura: ", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("CompraDialog", "Proveedor: ", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("CompraDialog", "Fecha: ", None, -1))
        self.productoExistenteRadioButton.setText(QtWidgets.QApplication.translate("CompraDialog", "Producto Existente:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("CompraDialog", "Codigo Producto: ", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("CompraDialog", "Cantidad:", None, -1))
        self.agregarProductoExistenteButton.setText(QtWidgets.QApplication.translate("CompraDialog", "Agregar Producto", None, -1))
        self.productoNuevoRadioButton.setText(QtWidgets.QApplication.translate("CompraDialog", "Nuevo Producto:", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("CompraDialog", "Descripcion Producto: ", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("CompraDialog", "Proveedor: ", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("CompraDialog", "Codigo Producto: ", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("CompraDialog", "Precio Lista:", None, -1))
        self.agregarProductoNuevoButton.setText(QtWidgets.QApplication.translate("CompraDialog", "Agregar Producto", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("CompraDialog", "Cantidad:", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("CompraDialog", "Lista de Productos en la Compra:", None, -1))
        self.borrarProductoButton.setText(QtWidgets.QApplication.translate("CompraDialog", "Borrar Producto", None, -1))
        self.okButton.setText(QtWidgets.QApplication.translate("CompraDialog", "OK", None, -1))
        self.cancelButton.setText(QtWidgets.QApplication.translate("CompraDialog", "Cancel", None, -1))

