# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Fri Jan 11 01:09:17 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 593)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.price_list_tab = QtWidgets.QWidget()
        self.price_list_tab.setObjectName("price_list_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.price_list_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableviewLayout = QtWidgets.QVBoxLayout()
        self.tableviewLayout.setObjectName("tableviewLayout")
        self.tableView = QtWidgets.QTableView(self.price_list_tab)
        self.tableView.setObjectName("tableView")
        self.tableviewLayout.addWidget(self.tableView)
        self.gridLayout_2.addLayout(self.tableviewLayout, 2, 0, 1, 1)
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setObjectName("filterLayout")
        self.label = QtWidgets.QLabel(self.price_list_tab)
        self.label.setObjectName("label")
        self.filterLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.price_list_tab)
        self.lineEdit.setObjectName("lineEdit")
        self.filterLayout.addWidget(self.lineEdit)
        self.gridLayout_2.addLayout(self.filterLayout, 1, 0, 1, 1)
        self.tabWidget.addTab(self.price_list_tab, "")
        self.inventario_tab = QtWidgets.QWidget()
        self.inventario_tab.setObjectName("inventario_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.inventario_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.inventario_tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.inventario_tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView_2 = QtWidgets.QTableView(self.inventario_tab)
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_2.addWidget(self.tableView_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 1, 2, 1)
        self.tabWidget.addTab(self.inventario_tab, "")
        self.compras_tab = QtWidgets.QWidget()
        self.compras_tab.setObjectName("compras_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.compras_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.compras_tab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.compras_tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableView_3 = QtWidgets.QTableView(self.compras_tab)
        self.tableView_3.setObjectName("tableView_3")
        self.verticalLayout_4.addWidget(self.tableView_3)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.compras_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setMinimumSize(QtCore.QSize(200, 200))
        self.label_2.setMaximumSize(QtCore.QSize(200, 200))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../enginecode/resources/images/IMG_8545.PNG"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1001, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionImportar_Lista_de_Precios = QtWidgets.QAction(MainWindow)
        self.actionImportar_Lista_de_Precios.setObjectName("actionImportar_Lista_de_Precios")
        self.actionImportar_Lista = QtWidgets.QAction(MainWindow)
        self.actionImportar_Lista.setObjectName("actionImportar_Lista")
        self.mainToolBar.addAction(self.actionImportar_Lista)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Filtro de Busqueda", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.price_list_tab), QtWidgets.QApplication.translate("MainWindow", "Lista de Precios", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Filtro de Busqueda", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inventario_tab), QtWidgets.QApplication.translate("MainWindow", "Inventario", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Nueva Compra", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "Editar Compra", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.compras_tab), QtWidgets.QApplication.translate("MainWindow", "Compras", None, -1))
        self.actionImportar_Lista_de_Precios.setText(QtWidgets.QApplication.translate("MainWindow", "Importar Lista de Precios", None, -1))
        self.actionImportar_Lista.setText(QtWidgets.QApplication.translate("MainWindow", "Importar Lista", None, -1))
        self.actionImportar_Lista.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Importar Lista", None, -1))

